const navigation = {
	HOME: "Home",
	ABOUT_US: "About Us",
	PARTNERS: "Partners",
	MEMBER_SERVICE: "Member Service",
	CPD_TRAINING: "CPD Activity",
	TRAINING_AND_COURSES: "Training and Courses",
	EVENT: "Event",
	NEWS: "Latest News",
	BECOMING_MEMBER: "Become a Member",
	LOGIN_SIGNUP: "Login/Sign Up",
	ONLINE_PAYMENT: "Online Payment",
	DOWNLOAD_CENTER: "Downloads",
	AGREE_TO_USE_VAI_CLINIC_TEXT: "By Signing in, you agree to use V·AI Clinic in accordance with the ",
	SIGN_IN: "Sign In",
	SIGN_OUT: "Sign Out",
	USERNAME: "Username",
	PASSWORD: "Password",
	FORGET_PASSWORD: "Forgot Password?",
	AND: " and ",
	PLEASE_ENTER_YOUR_USERNAME: "Please enter your username",
	PLEASE_ENTER_YOUR_PASSWORD: "Please enter your password",
	CLINIC: "Clinic",
	PRACTITIONER_PROFILE: "Practitioner Profile",
	CONTACT_US: "Contact Us",
	GO_BACK: "Go Back",
	ADD_PATIENT: "Add Patient",
	SELECT_CLINIC_TO_WORK: "Select Clinic to Work",
};

const prescription = {
	PRESCRIPTION: 'Medical History',
	PATIENT_PRESCRIPTION: "Patient's Medical History",
	DOCTOR_PRESCRIPTION: 'Doctor Prescription',
	NO_PRESCRIPTION_FOUND: 'No Prescription Found',
	PRESCRIPTION_NOT_FOUND: 'Prescription Not Found',
	"EDIT_NOW_HISTORY_#X": 'Editing Medical History #{{X}} Now',
	EDITING_NOW: 'Editing Now',
	NO_ENGLISH_ENTRY: 'No English Entry',
	NO_CHINESE_ENTRY: 'No Chinese Entry',
	ENGLISH_CONTENT: 'English Content',
	CHINESE_CONTENT: 'Chinese Content',
}

const search = {
	SEARCH: 'Search',
	SEARCH_PLACEHOLDER: 'Search',
	SEARCH_RESULT: 'Search Result',
	NO_SEARCH_RESULT: 'No Search Result',
	SEARCHING: 'Searching',
	SEARCH_PATIENT: 'Search Patient',
	SEARCH_FOR_PATIENT_IN_TOP_SEARCH_BAR_OR_NEW_PATIENT_HERE: "Search for a patient below by their patient name, or add a new patient using the button on the left.",
	SEARCH_PATIENT_BY_NAME: "Search patient by name",
	NO_PATIENT_FOUND: "No patient found",
	SEARCHING_PATIENT: "Searching for patient",
}

const info = {
	DOB: 'Date of Birth',
	DATE_OF_BIRTH: 'Date of Birth',
	SELECT_PATIENT: 'Select Patient',
	X_PRESCRIPTION_INFO: 'Prescription Info of {{X}}',
	VIEW_DETAILS: 'View Details',
	'MEDICAL_HISTORY_#X': 'Medical History #{{X}}',
	LAST_MODIFIED_BY_X_AT_Y: 'Last modified by {{X}} at {{Y}}',
	NEW_MEDICAL_HISTORY: 'New Medical History',
	NOT_SAVED_YET: 'Not Saved Yet',
	SAVE_HISTORY: 'Save History',
	PATIENT_INFO: 'Patient Info',
	PATIENT_ID: 'Patient ID',
	GENDER: 'Gender',
	MALE: 'Male',
	FEMALE: 'Female',
	MEDICAL_HISTORY: 'Medical History',
	APPOINTMENT: 'Appointment History',
	NO_HISTORY_FOUND: 'No History Found',
	DESCRIPTION: 'Personal Description',
	COMPLAINTS_SYMPTOMS: 'Complaints/Symptoms',
	DIAGNOSIS: 'Diagnosis',
	TREATMENT: 'Treatment',
	ENGLISH_CONTENT_GOES_HERE: 'English content goes here',
	CN_CONTENT_GOES_HERE: 'Chinese content goes here',
	EDITING: 'Editing',
	SIGNS_DIAGNOSIS: 'Signs and Diagnosis',
	TREATMENT_STRATEGIES: 'Treatment Strategies',
	ACUPUNCTURE_POINTS_DURATION_METHODS: 'Acupuncture Points, Duration and Methods',
	MOXIBUSTION: 'Moxibustion',
	THERAPEUTICAL_MASSAGE: 'Therapeutical Massage',
	GUA_SHA: 'Gua Sha',
	OTHER: 'Other',
	REMARKS: 'Remarks',
	TRANSLATE_FROM_X: 'Translated from {{X}}',
	TRANSLATE_TO_X: 'Translate to {{X}}',
	TRANSLATE: 'Translate',
	CHINESE: 'Chinese',
	ENGLISH: 'English',
	TRANSLATION_CONFIRM: 'Translation Confirm',
	TRANSLATED_CONTENT_WILL_BE_APPLIED_OVERWRITE_UR_EXISTING_CONTENT: 'Translated content will be applied and overwrite your existing content.',
	TRANSLATE_FROM_X_TO_Y: 'Translated from {{X}} to {{Y}}',
	ARE_YOU_SURE_TO_TRANSLATE: 'Are you sure to translate',
	INFO_FILLED: 'Information saved',
	NO_DATA_FOUND: 'No Data Found',
	FULL_CONTENT_X: 'Full Medical Record: {{X}}',
	"UPDATE_HISTORY_#X": 'Update Medical History #{{X}}',
	EDIT_DESCRIPTION: 'Edit Personal Description',
	EDIT_PATIENT: 'Edit Patient',
	BASIC_INFO: 'Basic Info',
	FIRST_NAME: 'First Name',
	LAST_NAME: 'Last Name',
	CONTACT_DETAIL: 'Contact Detail',
	RESIDENTIAL_ADDRESS: 'Residential Address',
	EMERGENCY_CONTACT_DETAIL: 'Emergency Contact Detail',
	RELATIONSHIP: 'Relationship',
	PATIENT_DISCLOSE: 'Patient Disclose',
	GUARDIAN_NAME: 'Guardian Name',
	GUARDIAN: 'Guardian',
	GUARDIAN_CONTACT_NUMBER: 'Guardian Contact Number',
	GUARDIAN_MOBILE: 'Guardian Mobile',
	REFERRED_BY: 'Referred By',
	NO_INSURANCE: 'No Insurance',
	EMERGENCY_CONTACT_PERSON: 'Emergency Contact Person',
	EMERGENCY_CONTACT_NUMBER: 'Emergency Contact Number',
	INSURANCE_INFO: 'Insurance Info',
	MORE_DETAILS: 'More Details',
	INSURANCE_X: 'Insurance {{X}}',
	COMPANY_NAME: 'Company Name',
	INSURANCE_NO: 'Insurance No',
	EXPIRY_DATE: 'Expiry Date',
	ADD_INSURANCE: 'Add Insurance',
	CANCEL: 'Cancel',
	CONFIRM: 'Confirm',
	SELECT_TEMPLATE: 'Select Website Template',
	ADD_TEMPLATE: 'Add Template',
	EDIT_TEMPLATE: 'Edit Template',
	PUBLISH_WEBSITE: 'Publish Website',
	VIEW_PUBLISHED_WEB: 'Preview Published Website',
	TEMPLATE: 'Template',
	INSURANCE: 'Insurance',
	EXPIRED_IN: 'Expired in',
	EXIT_EDIT: 'Exit Edit',
	X_VERSION: '{{X}} Version',
	MAKE_APPOINTMENT: 'Make Appointment',
	AI_TRANSLATE: 'AI Translate',
	EDIT_TITLE: 'Edit Title',
	EDIT_NAME: 'Edit Name',
	EDIT_INTRODUCTION: 'Edit Brief Description',
	ADD_SKILL: 'Add Top Skill',
	SKILL: 'Skill',
	AI_ENQUIRY: 'AI Inquiry',
	EDIT_AVATAR: 'Edit Profile Image',
	EDIT_CLINIC: 'Edit Clinic',
	MY_STRENGTHS: 'My Strengths',
	STANDARD_TREATMENT: 'Treatment Features',
	ACADEMIC: 'Academic',
	PATIENT_REVIEW: 'Patient Review',
	CLINIC_INFO: 'Clinic Info',
	EDIT_STRENGTHS: 'Edit Strengths',
	EDIT_TREATMENT: 'Edit Treatment',
	DR_X_ARTICLE: "{{X}}'s Article",
	COURSES: 'Courses',
	ARTICLES: 'Articles',
	EDIT_COURSE: 'Edit Course',
	UPLOAD_REVIEW_BG: 'Upload Review Background Image',
	EDIT_REVIEW: 'Edit Patient Review',
	PATIENT: 'Patient',
	TITLE: 'Title',
	SAVE_SUCCESS: 'Save Success',
	CLINIC_NAME: 'Clinic Name',
	PIN_TO_DISPLAY: 'Pin to Display',
	DELETE: 'Delete',
	SUBURB: 'Suburb',
	POSTCODE: 'Postcode',
	STATE: 'State',
	ADD: 'Add',
	MOVE_DOWN: 'Move Down',
	MOVE_UP: 'Move Up',
	SPECIALITY: 'Speciality',
	PUBLISHED: 'Published',
	HIDDEN: 'Hidden',
	READ: 'Read',
	ADD_ARTICLE: 'Add Article',
	SAVE: 'Save',
	PUBLISH: 'Publish',
	RE_UPLOAD_BG: 'Re-Upload Background Image',
	PATIENT_NAME: 'Patient Name',
	PATIENT_DESCRIPTION: 'Patient Description',
	REVIEW: 'Review',
	REUPLOAD_PROFILE_IMAGE: 'Re-Upload Profile Image',
	COURSE: 'Course',
	COURSE_TITLE: 'Course Title',
	START_DATE: 'Start Date',
	START_TIME: 'Start Time',
	DURATION: 'Duration',
	COURSE_TYPE: 'Course Type',
	OFFLINE_COURSE: 'Offline Course',
	ONLINE_COURSE: 'Online Course',
	MEETING_URL: 'Course Link',
	LOCATION: 'Location',
	STRENGTH: 'Strength',
	EXIT_PREVIEW: 'Exit Preview',
	MY_PROFILE: 'My Profile',
	PURE_HARMONY: 'Clean and Professional Template',
	HERB_ESSENCE: 'Fresh and Sophisticated Template',
	IM_WORKED_AT: " I'm working at",
	START_WORKING: 'Start Working',
	TOOLBAR: 'Toolbar',
	COLLAPSE_TOOLBAR: 'Collapse Toolbar',
	EDIT_URL: 'Edit URL',
	SLUG: 'Slug',
	EDIT_SLUG: 'Edit Profile Page URL',
	PUBLISH_CONFIRM: 'Publish Confirm',
	UNPUBLISH_CONFIRM: 'Unpublish Confirm',
	ARE_YOU_SURE_TO_X_WEBSITE: 'Are you sure to {{X}} website?',
	WEBSITE_WILL_BE_PUBLISHED_AND_VISIBLE_TO_PUBLIC_VIA_BELOW_LINK: 'Website will be published and visible to public via below link',
	WEBSITE_WILL_BE_UNPUBLISHED_AND_HIDDEN_FROM_PUBLIC: 'Website will be unpublished and hidden from public',
	U_CAN_STILL_PUBLISH_THE_WSBSITE_LATE_IF_U_WISH: 'You can still publish the website later if you wish',
	PUBLISH_S: 'publish',
	UNPUBLISH_S: 'unpublish',
	UNPUBLISH_WEBSITE: 'Unpublish Website',
	UNPUBLISHED: 'Unpublished',
	SWITCH_YOUR_TEMPLATE_PUBLISHED: 'Select a new webpage template to publish.',
	CLOSE_EDITOR: 'Close Editor',
	CLOSE: 'Close',
	REMOVE_SUCCESS: 'Remove Success',
	VIEW_ALL_X_CLINICS: 'View All {{X}} Clinics',
	CONTINUE: 'Continue',
	ONLY_WORKING_WEEKDAY: 'Only Working Weekday',
	WORKING_TIME: 'Working Time',
	WORKING_IN_WHOLE_WEEK: 'Working all Week',
	MONDAY: 'Mon',
	TUESDAY: 'Tue',
	WEDNESDAY: 'Wed',
	THURSDAY: 'Thu',
	FRIDAY: 'Fri',
	SATURDAY: 'Sat',
	SUNDAY: 'Sun',
	WORKING_TODAY: 'Set as Working Day',
	END_TIME: 'End Time',
	APPLY_WORKING_TIME_TO_ALL_DAYS: 'Apply Working Hours to All Days',
	ONLY_WORK_IN_WEEKDAYS: 'Only Work in Weekdays',
	WORK_IN_WHOLE_WEEK: 'Work all Week',
	CURRENT_WORKING_TIME_APPLIED_TO_ALL_DAYS: 'Current working time has been applied to all days',
	DR_X_COURSE: "{{X}}'s Courses",
	DELETE_ARTICLE: 'Delete Article',
	ARE_YOU_SURE_TO_DELETE_ARTICLE: 'Are you sure to delete this Article?',
	THIS_ACTION_CANNOT_BE_UNDONE: 'This action cannot be undone',
	SAVE_ARTICLE: 'Save Article',
	SAVE_ARTICLE_AND_PUBLISH: 'Save Article and Publish',
	PUBISH_ARTICLE: 'Publish Article',
	UNPUBLISH_ARTICLE: 'Unpublish Article',
	PUBLISH_ARTICLE: 'Publish Article',
	ARE_YOU_SURE_TO_X_ARTICLE: 'Are you sure not to {{X}} article?',
	VISITORS_WILL_NOT_BE_ABLE_TO_VIEW_THIS_ARTICLE: 'Visitors will not be able to view this article',
	VISITORS_WILL_BE_ABLE_TO_VIEW_THIS_ARTICLE: 'Visitors will be able to view this article',
	UNPUBLISH: 'Unpublish',
	REMOVE_BG_IMAGE: 'Remove Background Image',
	ARE_YOU_SURE_TO_REMOVE_BG_IMAGE: 'Are you sure to remove the background image?',
	BG_UPLOAD: 'Upload the background image',
	DEFAULT_BG_WILL_BE_APPLIED: 'Defalut background image will be applied',
	U_ARE_PREPARED_TO_TRANSLATE_UR_WEBSITE_CONTENT: 'You are prepared to translate your website content',
	WARNING: 'Warning',
	IF_YOU_HAVE_INPUTTED_ANY_TEXT_INTO_THE_LANGUAGE_YOU_SELECTED_WILL_BE_OVERWRITTEN: 'If you have inputted any text into the language you selected will be overwritten',
	I_UNDERSTAND_THE_ACTION_AND_AGREE_TO_TRANSLATE_USING_AI: 'I understand the action and agree to translate using AI',
	ALL_7_DAYS: 'All 7 Days',
	ARTICLE_TITLE: 'Article Title',
	NO_WORKING_DAYS: 'No Working Days',
	WEBSITE_PUBLISHED: 'Website published',
	WEBSITE_UNPUBLISHED: 'Website unpublished',
	TEMPLATE_SWITCHED_AND_PUBLISHED: 'Template updated and published',
	TRANSLATING_X_PLS_BE_PATIENT: 'Translating {{X}}. Please wait...',
	SAVING_TRANSLATION: 'Saving translation. Please wait...',
	TOGGLE_LANGUAGE: 'Switch Language',
	TRANSLATE_UR_WEBSITE_USING_AI: 'Translate your website using AI...',
	ARTICLE: "Article",
	VIEW_PATIENT_HISTORY: "View Patient History",
	PRESCRIPTION_INFO: "Medical History Info",
	TRANSLATE_FROM: "Translated from",
	TRANSLATE_TO: "Translated to",
	SWAP: "Swap",
}

const notification = {
	CLINIC_SWITCHED_TO_X: 'Current clinic has been switched to {{X}}',
	ONLY_IMAGE_FILES_ALLOWED: 'You can only upload image files here',
	HISTORY_SAVED: 'Medical history saved',
	TRANSLATION_COMPLETED: 'Translation completed',
	"UPDATE_HISTORY_#X": 'Update History #{{X}}',
	ARTICLE_TITLE_CANNOT_BE_EMPTY: 'Article title cannot be empty',
	ARTICLE_UPDATED: 'Article updated',
	ARTICLE_CREATED: 'Article created',
	ARTICLE_PUBLISHED: 'Article published',
	ARTICLE_UNPUBLISHED: 'Article unpublished',
	ARTICLE_DELETED: 'Article deleted',
	PREVIEW_TEMPLATE: 'Preview Mode',
	U_R_IN_PREVIEW_MODE: 'You are in preview mode',
	U_R_IN_EDIT_MODE: 'You are in edit mode',
	PROFILE_IMAGE_UPLOADED: 'Profile image uploaded',
	SAVE_SUCCESS: 'Save success',
	INCORRECT_USERNAME_OR_PASSWORD: 'Incorrect username or password',
	CLINIC_X_SELECTED: 'Clinic {{X}} selected for work',
	AUTHENTICATION_EXPIRED: 'Authentication expired! Please try re-login again',
	MAKE_AN_APPOINTMENT: 'Make an appointment',
	APPOINTMENT_TIME: 'Appointment Time',
	PHONE: 'Phone',
	EMAIL: 'Email',
	FIRST_NAME_IS_REQUIRED: 'First name is required',
	LAST_NAME_IS_REQUIRED: 'Last name is required',
	PHONE_IS_REQUIRED: 'Phone is required',
	INVALID_PHONE_NUMBER: 'Invalid phone number',
	PLEASE_FIX_ERRORS: 'Please fix the errors',
	BOOKING_CREATED: 'Booking created',
	FIRSTNAMEEN_IS_REQUIRED: 'First name (English) is required',
	LASTNAMEEN_IS_REQUIRED: 'Last name (English) is required',
	INVALID_EMAIL: 'Invalid email',
	EMAIL_IS_REQUIRED: 'Email is required',
	ADDRESS_IS_REQUIRED: 'Address is required',
	LESS_DETAILS: 'Less Details',
	REMOVE: 'Remove',
	COMPANY_NAME_IS_REQUIRED: 'Company name is required',
	INSURANCE_NUMBER_IS_REQUIRED: 'Insurance number is required',
	CONFIGURATION: 'Configuration',
	SELECT_SECTION_U_ARE_GOING_TO_CONFIGURE: 'Select the section you are going to configure',
	BUSINESS: 'Business',
	CONFIGURE_BUSINESS_TIME: 'Configure Business Time',
	LANGUAGE: 'Language',
	CURRENT_LANGUAGE_X: 'Current Language {{X}}',
	PATIENT_CREATED: 'Patient created',
	PATIENT_EDITED: 'Patient edited',
	CHECK_IN_SUCCESS: 'Check in success',
}

const appointment = {
	APPOINTMENT_INFO: 'Appointment Info',
	APPOINTMENT_STATUS: 'Appointment Status',
	CHECKED_IN: 'Checked In',
	CHECK_IN: 'Check In',
	PROCEED_TO_MEDICAL_HISTORY: 'Proceed to Medical History',
	APPOINTMENT_CLINIC: 'Appointment Clinic',
	NAME: 'Name',
	U_MIGHT_LOOKING_FOR_PATIENT: "👀 Are you looking for patient below?",
	NO_RELAVANT_PATIENT_IN_CLINIC: '👀 It looks like you have a new patient.',
	PLS_ADD_PATIENT_FIRST: 'Do you want to add him/her to your clinic?',
	SELECT_EXISTING_PATIENT_FROM_CLINIC_TO_CREATE_MEDICAL_HISTORY: 'Select patient from clinic to proceed in creating medical history',
	CREATE_MEDICAL_HISTORY: 'Create Medical History',
	NONE_OF_PATIENT_ABOVE_IS_CORRECT: 'None of the patient above?',
	PENDING_CHECK_IN: 'Pending Check In',
	ARE_YOU_SURE_TO_CHECK_IN_THIS_APPOINTMENT_FOR_X: 'Are you sure to check in to this appointment for {{X}}?',
	AFTER_CHECKED_IN_YOU_CAN_PROCEED_MEDICAL_HISTORY_FOR_THIS_PATIENT: 'After checked in, you can proceed to create medical history for this patient.',
	LOADING_APPOINTMENT: 'Loading Appointment',
	TODAY: 'Today',
	MASSAGE: 'Massage',
	ACUPUNCTURE: 'Acupuncture',
	CHINESE_MEDICINE: 'Chinese Medicine',
	APPROXIMATE_DURATION: 'Approximate Duration',
	APPROX: 'Approx.',
	BUSINESS_TIME: 'Business Time',
	WORKING_SERVICES: 'Working Services',
	WORKING_DAYS: 'Working Days',
	WORKING_TIME_PERIOD: 'Working Time Period',
	RESET: 'Reset',
	BLOCK_TIME_SLOTS: 'Block Time Slots',
	APPLY_BLOCK_TIMES_TO_ALL_DAYS: 'Apply Block Times to All Days',
	LOADING_TIME_SLOTS: 'Loading Time Slots',
	NO_AVAILABLE_TIME: 'No Available Time',
	RESET_CLINIC: 'Reset Clinic',
	CLINIC_NOT_FOUND: 'Clinic Not Found',
	SAVE_CLINIC_SUCCESS: 'Save Clinic Success',
	PLEASE_SELECT_WORKING_SERVICES: 'Please select working services',
	START_TIME_CANNOT_BE_AFTER_END_TIME: 'Start time cannot be after end time',
	END_TIME_CANNOT_BE_BEFORE_START_TIME: 'End time cannot be before start time',
	SELECTED_WEEKDAY: 'Selected Weekday',
	MINUTES: 'min',
	CLEAR_ALL: 'Clear All',
	CLICK_ON_TIMESLOT_THAT_YOU_DONT_WANT_IT_BE_AVAILABLE_FOR_APPOINTMENT: 'Click on the timeslot that you don\'t want it to be available for appointment',
	SELECT_WORKING_DAY: 'Select Working Day',
	DECREASE_DURATION: 'Decrease Duration',
	INCREASE_DURATION: 'Increase Duration',
	CURRENT_BLOCK_TIME_APPLIED_TO_ALL_DAYS: 'Current block time has been applied to all days',
	SAVE_AS_NOT_WORKING: 'Save as Not Working',
	SAVE_AS_WORKING: 'Save as Working',
	CONFIRM_CLEAR_BLOCK_TIMES: 'Are you sure to clear all block times?',
	CHANGING_DURATION_WILL_CLEAR_ALL_BLOCK_TIMES: 'Changing duration will clear all block times',
	CHANGING_WORKING_TIME_WILL_CLEAR_TODAY_BLOCK_TIMES: 'Changing working time will clear today\'s block times',
	BLOCK_TIMES_CLEARED: 'Block times cleared',
	SAVING: 'Saving',
	BLOCK_THIS_TIMESLOT: 'Block this timeslot',
	UNSAVED_CHANGES: "Unsaved Changes",
	YOU_HAVE_UNSAVED_CHANGES_CONTINUE: "You have unsaved changes. Are you sure you want to switch clinics and discard them?",
	DISCARD_AND_SWITCH: "Discard and Switch",
	USER_PROFILE: "User Profile",
	PATIENT_PROFILE: "Patient Profile",
	APPOINTMENT_HISTORY: "Appointment History",
	PERSONAL_INFO: "Personal Info",
	USERNAME: "Username",
	PASSWORD: "Password",
	CURRENT_PASSWORD: "Current Password",
	NEW_PASSWORD: "New Password",
	CONFIRM_NEW_PASSWORD: "Confirm New Password",
	NO_USERNAME: "No Username",
	NO_PASSWORD: "No Password",
	ADDRESS: "Address",
	EMERGENCY_CONTACT: "Emergency Contact",
	MY_INSURANCE: "My Insurance",
	COMPANY_NAME_PLACEHOLDER: "Company Name place holder",
	SAVE_ALL: "Save All",
	WELCOME_BACK: "Welcome Back",
	PLEASE_FILL_ALL_REQUIRED_FIELDS: "Please fill all required fields",
	SIGN_UP_TO_JOIN_US: "Sign up",
	WELCOME: "Welcome",
	ADD_AVATAR: "Add Avatar",
	CLICK_TO_UPLOAD: "Click to Upload",
	UPLOAD_AVATAR: "Upload Avatar",
	SIGN_UP: "Sign Up",
	BACK_TO_HOME: "Back to Home",




}

export default {
	translation: {
		...navigation,
		...prescription,
		...search,
		...info,
		...notification,
		...appointment,
		BACK: 'Back',
		CLOSE: 'Close',
		ONLINE_ZOOM_MEETING: 'Online Zoom Meeting',
		KEY_MEMBERS: 'Key Members',
		INTRODUCTION: ' Brief Introduction',
		LOAD_MORE: 'Load More',
		CURRENT: 'Current',
		HISTORY_EVENT: 'History Events',
		HISTORY_CPD: 'History CPD',
		HISTORY: 'In the Past',
		EXPIRED: 'Expired',
		MONTH_FORMAT: 'MMMM',
		EDIT: 'Edit',
		FROM: 'From',
		TO: 'To',
		TOTAL_X: 'Total {{X}} Records',
		OTHER_LANGUAGE_VERSION: '中文版',
		CLINIC: 'Clinic',
		HRS: "hrs",
		VIEW: 'View',
		LOADING: 'Loading',
		VIEW_ALL: 'View All',
		SWITCH_TEMPLATE: 'Switch Template',
		TERMS_AND_CONDITIONS: 'Terms and Conditions',
		PRIVACY_POLICY: 'Privacy Policy',
		INITIATING: 'Initiating',
		FAILED_TO_ACCESS_MICROPHONE: 'Failed to access microphone',
		LISTENING: 'Listening',
		TRANSCRIBING: 'Transcribing',
		SPEECH_TO_TEXT: 'Speech to Text',
		STOP_RECORDING: 'Stop Recording',
	}
};